### ISSUE TITLE
libavtransport implementation tracker

### ISSUE THREAD

**Issue by cyanreg** [cyanreg/avtransport#4]
libavtransport current status:
 - [ ] I/O
   * [x] FILE *
   * [x] fd
   * [x] UNIX socket
   * [x] Network socket
   * [x] mmap
   * [ ] liburing
   * [x] Callback-based
 - [ ] Protocols
   * [x] Datagram stream
   * [x] Stream (file)
     - [ ] Seeking
   * [ ] Quic (via OpenSSL)
   * [ ] Packet reordering for UDP and Quic
   * [ ] Callback-based
 - [ ] Output
   * [x] Packet scheduling
   * [x] Compression
   * [x] Session start
   * [x] Stream registration
   * [x] Stream data
   * [x] Font data
   * [x] Cube LUT
   * [x] ICC profile
   * [x] Video orientation
   * [x] Video information
   * [ ] Metadata
   * [x] LDPC encode
   * [ ] FEC parity
   * [ ] FEC grouping
 - [ ] Input
   * [ ] Decompression
   * [x] Session start
   * [ ] Stream registration
   * [x] Stream data
   * [x] Font data
   * [x] Cube LUT
   * [x] ICC profile
   * [x] Video orientation
   * [x] Video information
   * [ ] Metadata
   * [ ] LDPC encode
   * [ ] FEC parity
   * [ ] FEC grouping
 - [ ] Robustness
   * [ ] Input reordering
   * [ ] Packet lifetime
   * [ ] Global sequence overflow considerations
   * [ ] Fuzzing
 - [ ] Reliability
   * [ ] Retransmission
   * [ ] LDPC smart bit weighting (more confidence in bits likely to be correct)
  - [ ] Optimizations
    * [ ] LDPC
      - [ ] SSE
      - [ ] AVX2
      - [ ] AArch64
      - [ ] RISC-V
    * [ ] FEC (RaptorQ)
      - [ ] SSE
      - [ ] AVX2
      - [ ] AArch64
      - [ ] RISC-V
    * [ ] Faster packet delimiting for corrupt files
